//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Sensor;
using RosMessageTypes;
using UnityEngine;
using RosMessageTypes.Std;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class TempMsg : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/TempMsg";
        public override string RosMessageName => k_RosMessageName;

        public TemperatureMsg msg;


        public TempMsg()
        {

            RosMessageTypes.BuiltinInterfaces.TimeMsg time = new RosMessageTypes.BuiltinInterfaces.TimeMsg( 45 ,  58 );
            HeaderMsg header = new HeaderMsg(0,time,"frame0");
            msg = new TemperatureMsg(header ,0 ,0);
        }

        public TempMsg( double temperature, double variance)
        {
            float time1 = Time.time;
            //Debug.Log(time1);
            RosMessageTypes.BuiltinInterfaces.TimeMsg time = new RosMessageTypes.BuiltinInterfaces.TimeMsg((uint)time1, (uint)time1/1000);
            HeaderMsg header = new HeaderMsg(0, time, "map");
            msg =new TemperatureMsg( header, temperature, variance);
        }

        public static TempMsg Deserialize(MessageDeserializer deserializer) => new TempMsg(deserializer);
        private TempMsg(MessageDeserializer deserializer)
        {
            var desriallizedMsg = TemperatureMsg.Deserialize(deserializer);
            this.msg = new TemperatureMsg(desriallizedMsg.header,desriallizedMsg.temperature,desriallizedMsg.variance);
            

        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.msg);

        }

        public override string ToString()
        {
            return "Temperature : " + (this.msg).ToString() ;
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }

    }

}