//Do not edit! This file was generated by Unity-ROS MessageGeneration.
/*
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class TempMsgMsg : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/TempMsg";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public double temperature;
        public double variance;

        public TempMsgMsg()
        {
            this.header = new Std.HeaderMsg();
            this.temperature = 0.0;
            this.variance = 0.0;
        }

        public TempMsgMsg(Std.HeaderMsg header, double temperature, double variance)
        {
            this.header = header;
            this.temperature = temperature;
            this.variance = variance;
        }

        public static TempMsgMsg Deserialize(MessageDeserializer deserializer) => new TempMsgMsg(deserializer);

        private TempMsgMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.temperature);
            deserializer.Read(out this.variance);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.temperature);
            serializer.Write(this.variance);
        }

        public override string ToString()
        {
            return "TempMsgMsg: " +
            "\nheader: " + header.ToString() +
            "\ntemperature: " + temperature.ToString() +
            "\nvariance: " + variance.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
*/