//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Geometry;
using UnityEngine;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [System.Serializable]
    public class VelMsgMsg : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/VelMsg";
        public override string RosMessageName => k_RosMessageName;
        [SerializeField]
        public Geometry.TwistMsg  msg;
 

        public VelMsgMsg()
        {
            Vector3Msg linear = new Vector3Msg(0, 0, 0);
            Vector3Msg angular = new Vector3Msg(0, 0, 0);
            this.msg = new TwistMsg(linear, angular);

        }
        public VelMsgMsg(TwistMsg msg)
        {
            this.msg = new TwistMsg(msg.linear ,msg.angular);
        }
        public VelMsgMsg(Vector3Msg linear, Vector3Msg angular)
        {
            this.msg = new TwistMsg(linear, angular);
        }

        public static VelMsgMsg Deserialize(MessageDeserializer deserializer) => new VelMsgMsg(deserializer);

        private VelMsgMsg(MessageDeserializer deserializer)
        {
             var desriallizedMsg = Geometry.TwistMsg.Deserialize(deserializer);
            this.msg = new TwistMsg(desriallizedMsg.linear, desriallizedMsg.angular);

        }
       
        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.msg);

        }
        public Vector3 LinearToVector3()
        {
            Vector3 linear = new Vector3( (float)this.msg.linear.x, (float)this.msg.linear.y, (float)this.msg.linear.z);
            return linear;
        }
        public Vector3 AngularToVector3()
        {
            Vector3 angular = new Vector3((float)this.msg.angular.x, (float)this.msg.angular.y, (float)this.msg.angular.z);
            return angular;
        }


        public override string ToString()
        {
            return "recived: " + this.msg.ToString();
            
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
